# Generated by Django 4.1.5 on 2023-02-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallets',
            new_name='Wallet',
        ),
    ]
