# Generated by Django 4.1.5 on 2023-02-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_wallets_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='ammount_currency',
            new_name='amount_currency',
        ),
    ]
