# Generated by Django 4.1.5 on 2023-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wallet_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount_currency',
            field=models.CharField(choices=[('rub', 'Rub'), ('kzt', 'Kzt'), ('usd', 'Usd')], default='kzt', max_length=3),
        ),
    ]
