# Generated by Django 4.1.5 on 2023-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wallet_amount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount_currency',
            field=models.CharField(choices=[('rub', 'руб'), ('kzt', 'тенге'), ('usd', 'доллары')], default='kzt', max_length=3),
        ),
    ]
